Revisões nas imagens
Paper-Street-Softwares/Template-Landpage-Front-2.0 pull request #188
Opened 2024-05-07 14:32 UTC by BiellSouza

2024-05-07 14:38 UTC, EdisonMatos requested changes

2024-05-07 14:38 UTC, EdisonMatos commented on package.json
> +    "primereact": "^10.6.5",
Esse código não deve vir nessa pr de revisão de imagem

2024-05-08 12:47 UTC, EdisonMatos requested changes

2024-05-08 12:47 UTC, EdisonMatos commented on src/components/sections/CtaWhatsapp.jsx
> +            <div className=" h-50 w-[90%] max-w-40 phone1:w-[100%] phone1:max-w-none phone3:max-w-60 tablet1:w-[45%]">
A classe h-50 não existe no tailwind

2024-05-08 14:12 UTC, BiellSouza commented on src/components/sections/CtaWhatsapp.jsx
> +            <div className=" h-50 w-[90%] max-w-40 phone1:w-[100%] phone1:max-w-none phone3:max-w-60 tablet1:w-[45%]">
resolvido

2024-05-08 14:13 UTC, BiellSouza commented on package.json
> +    "primereact": "^10.6.5",
resolvido

2024-05-08 14:22 UTC, closed without merging