Criar seção sobre nós
Paper-Street-Softwares/Template-Landpage-Front-2.0 pull request #20
Opened 2024-02-28 21:44 UTC by BiellSouza

2024-02-28 23:34 UTC, EdisonMatos requested changes

2024-02-28 23:34 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +          <h3 class=' font-mainFont font-medium leading-[1.5rem] text-paragraph4 tracking-[0rem] text-left'>Nossa História</h3>
Onde tiver "class" no código, trocar por "className". Ambos funcionam, mas o correto é usar className quando se usa React.

2024-03-04 19:16 UTC, EdisonMatos requested changes

2024-03-04 19:16 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +        <div className="textos w-[100%] h-[100%] gap-[10%] desktop1:w-[32%] desktop2:w-[47%] ">
Esse h-100% atende qual necessidade? Um h-auto já nao faria a mesma função? E se h-auto resolve, ele seria necessário?

2024-03-04 19:16 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +          <h3 className='texto-h3 pb-[3%] text-quaternary font-medium text-paragraph3 leading-[24%] phone3:pb-[2%] phone3:text-paragraph4 phone3:leading-[27%] desktop1:pb-[3%] '>Nossa História</h3>
Conferir classes que não estão sendo utilizadas pelo tailwind e remover

2024-03-04 19:16 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +          <h5 className='texto-h5 text-quaternary font-normal text-paragraph3 leading-[150%] phone3:text-paragraph4 desktop1:text-paragraph2 desktop2:text-paragraph3'>A Mpa é uma empresa familiar cri
Tag do tipo H é pra títulos. Muda a tag sendo usada aqui no texto

2024-03-04 21:37 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> +          <h3 className='texto-h3 pb-[3%] text-quaternary font-medium text-paragraph3 leading-[24%] phone3:pb-[2%] phone3:text-paragraph4 phone3:leading-[27%] desktop1:pb-[3%] '>Nossa História</h3>
Arrumado

2024-03-04 21:37 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> +          <h5 className='texto-h5 text-quaternary font-normal text-paragraph3 leading-[150%] phone3:text-paragraph4 desktop1:text-paragraph2 desktop2:text-paragraph3'>A Mpa é uma empresa familiar cri
Corrigido

2024-03-04 22:42 UTC, EdisonMatos requested changes
Ajustes necessários

2024-03-04 22:42 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +        <div className=" flex justify-center pt-[8%] phone1:w-[100%] phone1:h-[100%] phone3:pt-[5%] tablet1:pt-[4%] tablet2:pt-[3%] desktop1:pt-[2%] desktop1:w-[50%] desktop2:w-[40%]">
Esse h-100% pode ser removido, não?

2024-03-04 22:42 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> +          <p className=' text-quaternary font-normal text-paragraph3 leading-[150%] phone3:text-paragraph4 desktop1:text-paragraph2 desktop2:text-paragraph3'>A Mpa é uma empresa familiar criada espec
Identifiquei erros nos tamanhos das fontes em telas diferente, conforme figma. Se olhar lá, tem telas que os tamanhos das fontes mudam. Ex: Em 768px o tamanho do parágrafo deveria ser 14 e aqui está como 16, fora outros. Faz uma checagem de ajuste geral

2024-03-04 23:04 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> +        <div className=" flex justify-center pt-[8%] phone1:w-[100%] phone1:h-[100%] phone3:pt-[5%] tablet1:pt-[4%] tablet2:pt-[3%] desktop1:pt-[2%] desktop1:w-[50%] desktop2:w-[40%]">
Sim, removido

2024-03-04 23:05 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> +          <p className=' text-quaternary font-normal text-paragraph3 leading-[150%] phone3:text-paragraph4 desktop1:text-paragraph2 desktop2:text-paragraph3'>A Mpa é uma empresa familiar criada espec
Corrigido

2024-03-05 13:15 UTC, merged