fix: Corrige articleImage e articleParagraph
Paper-Street-Softwares/Template-Landpage-Front-2.0 pull request #29
Opened 2024-03-11 13:05 UTC by BiellSouza

2024-03-11 17:49 UTC, EdisonMatos requested changes

2024-03-11 17:49 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
>          sectionHeaderDescription="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old."
Faltou inserir o texto do componente Section Header conforme está no figma

2024-03-11 17:49 UTC, EdisonMatos commented on src/components/sectionElements/Article.jsx
> +
As margens continuando não estando fiel ao figma. Perceba que por poucos píxels não está igual, e pra nós essa diferença faz sentido.
No figma:
![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/a9e3619c-e34d-4ea7-b0d5-ef2b424e5339)

No seu código:
![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/364aa67f-dab8-4893-ba24-227e6066f586)

2024-03-11 17:49 UTC, EdisonMatos commented on src/components/sectionElements/Article.jsx
> +				<h3 className='pb-[3%] text-quaternary font-medium text-paragraph3 leading-[24%] phone3:pb-[2%] phone3:text-paragraph4 phone3:leading-[27%] desktop1:pb-[3%] '>{articleSubtitle}</h3>
Ao inspecionar o subtítulo, parece que o conteúdo está não está bem alocado dentro de um espaço correto. Está codado correto mesmo?
![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/164d268e-4f74-4a3b-b38c-b1a2c5703ad1)

2024-03-12 10:52 UTC, BiellSouza commented on src/components/sectionElements/Article.jsx
> +
Revisado

2024-03-12 21:23 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
>          sectionHeaderDescription="Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old."
Corrigido

2024-03-13 11:57 UTC, EdisonMatos commented on src/components/sectionElements/Article.jsx
> +	const articleImage = props.articleImage
articleImage não se refere a nada mais no código

2024-03-14 12:48 UTC, closed without merging