feat: Adiciona href ao link do botão (Ver todos) na Sessão Services
Paper-Street-Softwares/Template-Landpage-Front-2.0 pull request #321
Opened 2024-06-25 13:51 UTC by BiellSouza

2024-06-25 18:27 UTC, EdisonMatos requested changes

2024-06-25 18:27 UTC, EdisonMatos commented on src/content/services.jsx
Aqui você não inseriu href ao link do botão, você apenas escreveu no banco de dados uma propriedade e um valor, e não chamou ele em lugar nenhum. Por sinal, escreveu "herf", ao invés de href

2024-06-26 12:46 UTC, BiellSouza commented on src/content/services.jsx
Alterado

2024-06-27 11:40 UTC, EdisonMatos requested changes

2024-06-27 11:40 UTC, EdisonMatos commented on src/components/sections/NavbarSocial.jsx
> +                    href="https://wa.me/"
Esse href está errado, não é o que deve ser feito.

2024-07-01 13:18 UTC, merged