feat: Cria SectionArticle, ArticleComponent e aplica ambos na Aboutus
Paper-Street-Softwares/Template-Landpage-Front-2.0 pull request #67
Opened 2024-03-20 13:45 UTC by BiellSouza

2024-03-20 14:33 UTC, EdisonMatos requested changes
Request changes

2024-03-20 14:33 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
Estrutura demonstra que foi construido de forma irregular na visualização pra desktop. O final da palavra Volumes está vazando

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/5b8c7f61-9a43-4184-890b-2accf593386a)

2024-03-20 14:33 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> -            Nossa História
Mais uma vez, esse elemento segue construido de forma estranha, onde a letra vaza da área dele

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/5df8af98-dbf4-41c3-ac27-951ef545976a)

2024-03-20 14:33 UTC, EdisonMatos commented on src/components/sectionElements/SectionArticle.jsx
Distâncias verticais entre os ítens não estão de acordo

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/f556bdf4-f8c1-48f2-ab9b-4e5e9959a53d)

2024-03-20 14:33 UTC, EdisonMatos commented on src/components/sectionElements/SectionArticle.jsx
Outro cenário onde o espaçamento vertical não está de acordo

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/36cdcb3f-1720-44cf-9903-fc9a2dc9a3bf)

2024-03-20 22:01 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
Corrigido

2024-03-20 22:01 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> -            Nossa História
Corrigido

2024-03-20 22:01 UTC, BiellSouza commented on src/components/sectionElements/SectionArticle.jsx
Corrigido

2024-03-21 11:57 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> -            Nossa História
Continua com uma estrutura que não é a correta. Não tem porque ter padding aqui. Padding é internedo, e vc tá usando ele esperando que ele faça o que a margim faz

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/13cb26ce-fd9b-41f7-9b67-b76128bb04c8)

2024-03-21 11:58 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> -            Nossa História
Na tela de 768px continua o problema que apontei no início

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/2eed3b8a-bb90-4ff4-b8ce-13f7ad7ae1a5)

2024-03-21 11:59 UTC, EdisonMatos commented on src/components/sections/AboutUs.jsx
> -            Nossa História
Em outras telas também dá pra ver que a construção desse elemento n tá legal 

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/f057ef1d-1082-4c62-b128-0a428e3ebdb7)

2024-03-21 12:08 UTC, EdisonMatos requested changes

2024-03-21 12:08 UTC, EdisonMatos commented on src/components/sectionElements/ArticleComponent.jsx
Algo na resolução 1440px tá tirando o texto da área que deveria

![image](https://github.com/Paper-Street-Softwares/Template-Landpage-Front-2.0/assets/17342047/562d3201-2f29-4024-9009-faaef3cb8ce1)

2024-03-21 12:08 UTC, EdisonMatos commented on src/components/sectionElements/ArticleComponent.jsx
Ele deve acompanhar a linha pontilhada

2024-03-21 18:53 UTC, EdisonMatos requested changes
Revisar

2024-03-21 19:28 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
Corrigido

2024-03-21 19:28 UTC, BiellSouza commented on src/components/sections/AboutUs.jsx
> -            Nossa História
corrigido

2024-03-21 19:28 UTC, BiellSouza commented on src/components/sectionElements/ArticleComponent.jsx
corrigido

2024-03-21 19:49 UTC, merged